name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --immutable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/cache@v2
        id: build-cache
        with:
          path: |
            */*/dist
          key: ${{ runner.os }}-${{ hashFiles('**/src/**/*.ts*') }}
      - run: yarn install --immutable
      - name: build
        if: steps.build-cache.outputs.cache-hit != 'true'
        run: yarn run isbt
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --immutable
      - name: lint
        run: yarn lint
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/cache@v2
        id: build-cache
        with:
          path: |
            */*/dist
          key: ${{ runner.os }}-${{ hashFiles('**/src/**/*.ts*') }}
      - run: yarn install --immutable
      - name: test
        run: yarn test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish:
    needs: [build, test]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && github.event.head_commit.message == 'Publish' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/cache@v2
        id: build-cache
        with:
          path: |
            */*/dist
          key: ${{ runner.os }}-${{ hashFiles('**/src/**/*.ts*') }}
      - run: yarn install --immutable
      - name: publish
        if: steps.build-cache.outputs.cache-hit == 'true'
        run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  canary:
    needs: [build, test]
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' && github.event.head_commit.message == 'Publish' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/cache@v2
        id: build-cache
        with:
          path: |
            */*/dist
          key: ${{ runner.os }}-${{ hashFiles('**/src/**/*.ts*') }}
      - run: yarn install --immutable
      - name: publish
        if: steps.build-cache.outputs.cache-hit == 'true'
        run: yarn canary --preid pr${{ github.pull_request.number }} --dist-tag canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
