name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0
      - run: yarn install

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - run: yarn run isbt

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - run: yarn workspaces run jest --passWithNoTests

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[release]') }}
    steps:
      - run: yarn release
