name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.3.0
        with:
          cache: 'yarn'

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.3.0
        with:
          cache: 'yarn'
      - run: yarn run isbt

  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.3.0
        with:
          cache: 'yarn'
      - run: yarn workspaces run jest --passWithNoTests

  publish:
    needs: [build, test]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[release]') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.3.0
      - run: yarn release
